export class Setor {
    id: number;
    dataCadastro: string;
    id_empresa: number;
    codigo: string;
    descricao: string;
    id_tipo_setor: number;
    abreviado: string;
    tempo_por_operacao: number;
    horas_disponiveis_dia: number;
    horas_uso_dia: number;
    horas_dias_seg_sex: number;
    horas_sabado: number;
    dias_nomes: string;
    num_max_op_dia: number;
    valor_mao_obra: number;
    fator_utilizado: number;
    volume_maximo: number;
    num_equipamento_disponivel: number;
    potencia_instalada: number;
    consumo_eletricidade: number;
    valor_equipamento0: number;
    valor_equipamento1: number;
    valor_equipamento2: number;
    potencia_instalada_producao: number;
    potencia_instalada_apoio: number;
    consumo_eletricidade_producao: number;
    consumo_eletricidade_apoio: number;
    valor_equipamento_met0_producao: number;
    valor_equipamento_met0_apoio: number;
    valor_equipamento_met1_producao: number;
    valor_equipamento_met1_apoio: number;
    valor_equipamento_met2_producao: number;
    valor_equipamento_met2_apoio: number;
    valor_mao_obra_direta: number;
    valor_mao_obra_supervisao: number;
    valor_mao_obra_direta_producao: number;
    valor_mao_obra_supervisao_producao: number;
    valor_mao_obra_apoio: number;
    valor_material_indireto: number;
    valor_material_indapoio: number;
    valor_material_indprod: number;
    update: string;

    constructor() {  
        this.id = 0;
        this.dataCadastro = '';
        this.id_empresa = 0;
        this.codigo = '';
        this.descricao = '';
        this.id_tipo_setor = 0;
        this.abreviado = '';
        this.tempo_por_operacao = 0;
        this.horas_disponiveis_dia = 0;
        this.horas_uso_dia = 0;
        this.horas_dias_seg_sex = 0;
        this.horas_sabado = 0;
        this.dias_nomes = '';
        this.num_max_op_dia = 0;
        this.valor_mao_obra = 0;
        this.fator_utilizado = 0;
        this.volume_maximo = 0;
        this.num_equipamento_disponivel = 0;
        this.potencia_instalada = 0;
        this.consumo_eletricidade = 0;
        this.valor_equipamento0 = 0;
        this.valor_equipamento1 = 0;
        this.valor_equipamento2 = 0;
        this.potencia_instalada_producao = 0;
        this.potencia_instalada_apoio = 0;
        this.consumo_eletricidade_producao = 0;
        this.consumo_eletricidade_apoio = 0;
        this.valor_equipamento_met0_producao = 0;
        this.valor_equipamento_met0_apoio = 0;
        this.valor_equipamento_met1_producao = 0;
        this.valor_equipamento_met1_apoio = 0;
        this.valor_equipamento_met2_producao = 0;
        this.valor_equipamento_met2_apoio = 0;
        this.valor_mao_obra_direta = 0;
        this.valor_mao_obra_supervisao = 0;
        this.valor_mao_obra_direta_producao = 0;
        this.valor_mao_obra_supervisao_producao = 0;
        this.valor_mao_obra_apoio = 0;
        this.valor_material_indireto = 0;
        this.valor_material_indapoio = 0;
        this.valor_material_indprod = 0;
        this.update = '';
    }
}